[project]
name = "learning-spark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
    "pyspark>=4.0.0",
    "tqdm>=4.67.1",
]
